### ISSUE TITLE
A question about PWIM-main_sts

### ISSUE THREAD

**Issue by meperdine** [lanwuwei/SPM_toolkit#23]
Traceback (most recent call last):
  File "main_sts.py", line 893, in <module>
    main(args)
  File "main_sts.py", line 466, in main
    combine_mode, lm_mode)#, corpus)
TypeError: __init__() takes exactly 24 arguments (23 given)

请问这个问题怎么解决呢  我看是模型里缺了一个deepCNN的参数  这个应该怎么赋值呢  谢谢

**Comment by lanwuwei** [comment]
`model=DeepPairWiseWord(EMBEDDING_DIM,HIDDEN_DIM,1,task,granularity,num_class,dict,fake_dict, dict_char_ngram, oov,tokens, word_freq,
	                       feature_maps,kernels,charcnn_embedding_size,max_word_length,character_ngrams,c2w_mode,character_ngrams_overlap, word_mode,
	                       combine_mode, lm_mode, args.deep_CNN)#, corpus)`
